steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - CF-freecurrencyapi
  - --region=southamerica-east1
  - --source=freecurrencyapi/src/
  - --trigger-http
  - --runtime=RUNTIME
